services:
  stream-saver:
    build: .
    container_name: stream-saver
    network_mode: host
    environment:
      - STREAM_URL=https://vavooproxy.magnitude.workers.dev/resolve?url=https://vavoo.to/vavoo-iptv/play/38229012391e140a7f75ba
      - OUTPUT_FILE=/data/streams.m3u
      - TIMEOUT=5
    volumes:
      - ./streams_data:/data
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
