services:
  stream-saver:
    build: .
    container_name: stream-saver
    network_mode: host
    environment:
      - STREAM_URL=https://qmaalhy7acgxwhm.ngolpdkyoctjcddxshli469r.org/sunshine/VBOfJR3SsQ1ZyJDsLjOihaogQm_lGs-5HhAR7FuOjtd_w8sfoL4Cfz-mFtqwHk5Sdx2FStgbWek2szQLzJ5pf_5aoeLcui9nVf6HgL57WFDMikFHds0ky2GJfUW8UeAAGY7znzCb12Q6QlQAWiSJ_IqCYA8ZXf6cy0rvVXskWubish6mNl50ovtD1N9rYRCiaVoCV7LP4WOdsEM_XIDqxV-JhJMrirRl3251wuRAtcmbvKnK59JMo6A7qT4rq2n3QwWnY66HQXpaL9-gax6mbQeRv3KoZ10KGewUJaPcQDo/hls/index.m3u8
      - OUTPUT_FILE=/data/streams.m3u
      - TIMEOUT=5
    volumes:
      - ./streams_data:/data
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
